export const PERMISSION_RESOURCES = [
  "dashboard",
  "location",
  "carrier",
  "service-code",
  "route",
  "schedule",
  "rate",
  "rate-cost",
  "margin-rule",
  "customer",
  "quotation",
  "quotation-approval",
  "integration",
  "user",
  "role",
  "audit-log",
] as const;

export const PERMISSION_ACTIONS = [
  "read",
  "create",
  "update",
  "delete",
  "approve",
  "send",
  "import",
  "retry",
] as const;

export type PermissionResource = (typeof PERMISSION_RESOURCES)[number];
export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];
export type PermissionKey = `${PermissionResource}.${PermissionAction}`;

export const ROLE_CODES = [
  "system-admin",
  "rate-manager",
  "sales-manager",
  "sales-representative",
  "operations",
  "auditor",
] as const;

export type RoleCode = (typeof ROLE_CODES)[number];

export function isRoleCode(value: string): value is RoleCode {
  return (ROLE_CODES as readonly string[]).includes(value);
}

const READ_ONLY_PERMISSIONS = [
  "dashboard.read",
  "location.read",
  "carrier.read",
  "service-code.read",
  "route.read",
  "schedule.read",
  "rate.read",
  "customer.read",
  "quotation.read",
] as const satisfies readonly PermissionKey[];

export const ROLE_PERMISSIONS: Record<RoleCode, readonly PermissionKey[]> = {
  "system-admin": [
    "dashboard.read",
    "location.read",
    "location.create",
    "location.update",
    "location.delete",
    "carrier.read",
    "carrier.create",
    "carrier.update",
    "carrier.delete",
    "service-code.read",
    "service-code.create",
    "service-code.update",
    "service-code.delete",
    "route.read",
    "route.create",
    "route.update",
    "route.delete",
    "schedule.read",
    "schedule.create",
    "schedule.update",
    "schedule.delete",
    "rate.read",
    "rate.create",
    "rate.update",
    "rate.delete",
    "rate.import",
    "rate-cost.read",
    "margin-rule.read",
    "margin-rule.create",
    "margin-rule.update",
    "margin-rule.delete",
    "customer.read",
    "customer.create",
    "customer.update",
    "customer.delete",
    "quotation.read",
    "quotation.create",
    "quotation.update",
    "quotation.delete",
    "quotation.send",
    "quotation-approval.read",
    "quotation-approval.approve",
    "integration.read",
    "integration.create",
    "integration.update",
    "integration.delete",
    "integration.retry",
    "user.read",
    "user.create",
    "user.update",
    "user.delete",
    "role.read",
    "role.create",
    "role.update",
    "role.delete",
    "audit-log.read",
  ],
  "rate-manager": [
    "dashboard.read",
    "location.read",
    "carrier.read",
    "service-code.read",
    "route.read",
    "route.create",
    "route.update",
    "schedule.read",
    "schedule.create",
    "schedule.update",
    "rate.read",
    "rate.create",
    "rate.update",
    "rate.import",
    "rate-cost.read",
    "margin-rule.read",
    "margin-rule.create",
    "margin-rule.update",
    "customer.read",
    "quotation.read",
  ],
  "sales-manager": [
    ...READ_ONLY_PERMISSIONS,
    "rate-cost.read",
    "margin-rule.read",
    "customer.create",
    "customer.update",
    "quotation.create",
    "quotation.update",
    "quotation.send",
    "quotation-approval.read",
    "quotation-approval.approve",
  ],
  "sales-representative": [
    "dashboard.read",
    "location.read",
    "carrier.read",
    "service-code.read",
    "route.read",
    "schedule.read",
    "rate.read",
    "customer.read",
    "customer.create",
    "customer.update",
    "quotation.read",
    "quotation.create",
    "quotation.update",
    "quotation.send",
  ],
  operations: [
    "dashboard.read",
    "location.read",
    "carrier.read",
    "service-code.read",
    "route.read",
    "schedule.read",
    "schedule.create",
    "schedule.update",
    "rate.read",
    "integration.read",
    "integration.retry",
  ],
  auditor: [...READ_ONLY_PERMISSIONS, "integration.read", "audit-log.read"],
};

export function hasPermission(
  roleCodes: readonly RoleCode[],
  permission: PermissionKey,
) {
  return roleCodes.some((roleCode) =>
    ROLE_PERMISSIONS[roleCode].includes(permission),
  );
}
