export const CARRIER_SEEDS = [
  { code: "OCEAN-MAERSK", type: "OCEAN", nameKo: "머스크", nameEn: "Maersk", scac: "MAEU", iataCode: null },
  { code: "OCEAN-MSC", type: "OCEAN", nameKo: "MSC", nameEn: "Mediterranean Shipping Company", scac: "MSCU", iataCode: null },
  { code: "OCEAN-CMA", type: "OCEAN", nameKo: "CMA CGM", nameEn: "CMA CGM", scac: "CMDU", iataCode: null },
  { code: "OCEAN-COSCO", type: "OCEAN", nameKo: "코스코", nameEn: "COSCO Shipping Lines", scac: "COSU", iataCode: null },
  { code: "OCEAN-HAPAG", type: "OCEAN", nameKo: "하파그로이드", nameEn: "Hapag-Lloyd", scac: "HLCU", iataCode: null },
  { code: "OCEAN-ONE", type: "OCEAN", nameKo: "오션 네트워크 익스프레스", nameEn: "Ocean Network Express", scac: "ONEY", iataCode: null },
  { code: "OCEAN-EVERGREEN", type: "OCEAN", nameKo: "에버그린", nameEn: "Evergreen Marine", scac: "EGLV", iataCode: null },
  { code: "OCEAN-YANGMING", type: "OCEAN", nameKo: "양밍", nameEn: "Yang Ming Marine Transport", scac: "YMLU", iataCode: null },
  { code: "OCEAN-HMM", type: "OCEAN", nameKo: "HMM", nameEn: "HMM", scac: "HDMU", iataCode: null },
  { code: "OCEAN-PIL", type: "OCEAN", nameKo: "PIL", nameEn: "Pacific International Lines", scac: "PCIU", iataCode: null },
  { code: "OCEAN-WANHAI", type: "OCEAN", nameKo: "완하이라인", nameEn: "Wan Hai Lines", scac: "WHLC", iataCode: null },
  { code: "OCEAN-ZIM", type: "OCEAN", nameKo: "짐라인", nameEn: "ZIM Integrated Shipping Services", scac: "ZIMU", iataCode: null },
  { code: "AIR-KE", type: "AIRLINE", nameKo: "대한항공 카고", nameEn: "Korean Air Cargo", scac: null, iataCode: "KE" },
  { code: "AIR-OZ", type: "AIRLINE", nameKo: "아시아나항공 화물", nameEn: "Asiana Airlines Cargo", scac: null, iataCode: "OZ" },
  { code: "AIR-CX", type: "AIRLINE", nameKo: "캐세이 카고", nameEn: "Cathay Cargo", scac: null, iataCode: "CX" },
  { code: "AIR-SQ", type: "AIRLINE", nameKo: "싱가포르항공 카고", nameEn: "Singapore Airlines Cargo", scac: null, iataCode: "SQ" },
  { code: "AIR-EK", type: "AIRLINE", nameKo: "에미레이트 스카이카고", nameEn: "Emirates SkyCargo", scac: null, iataCode: "EK" },
  { code: "AIR-QR", type: "AIRLINE", nameKo: "카타르항공 카고", nameEn: "Qatar Airways Cargo", scac: null, iataCode: "QR" },
  { code: "AIR-LH", type: "AIRLINE", nameKo: "루프트한자 카고", nameEn: "Lufthansa Cargo", scac: null, iataCode: "LH" },
  { code: "AIR-CV", type: "AIRLINE", nameKo: "카고룩스", nameEn: "Cargolux", scac: null, iataCode: "CV" },
] as const;
