export const REGION_SEEDS = [
  { code: "NORTHEAST_ASIA", nameKo: "동북아", nameEn: "Northeast Asia" },
  { code: "SOUTHEAST_ASIA", nameKo: "동남아", nameEn: "Southeast Asia" },
  { code: "SOUTH_ASIA", nameKo: "남아시아", nameEn: "South Asia" },
  { code: "NORTH_AMERICA", nameKo: "북미", nameEn: "North America" },
  { code: "EUROPE", nameKo: "유럽", nameEn: "Europe" },
  { code: "MIDDLE_EAST", nameKo: "중동", nameEn: "Middle East" },
  { code: "OCEANIA", nameKo: "오세아니아", nameEn: "Oceania" },
] as const;

export const COUNTRY_SEEDS = [
  { iso2: "KR", iso3: "KOR", nameKo: "대한민국", nameEn: "South Korea", regionCode: "NORTHEAST_ASIA" },
  { iso2: "CN", iso3: "CHN", nameKo: "중국", nameEn: "China", regionCode: "NORTHEAST_ASIA" },
  { iso2: "JP", iso3: "JPN", nameKo: "일본", nameEn: "Japan", regionCode: "NORTHEAST_ASIA" },
  { iso2: "HK", iso3: "HKG", nameKo: "홍콩", nameEn: "Hong Kong", regionCode: "NORTHEAST_ASIA" },
  { iso2: "TW", iso3: "TWN", nameKo: "대만", nameEn: "Taiwan", regionCode: "NORTHEAST_ASIA" },
  { iso2: "SG", iso3: "SGP", nameKo: "싱가포르", nameEn: "Singapore", regionCode: "SOUTHEAST_ASIA" },
  { iso2: "VN", iso3: "VNM", nameKo: "베트남", nameEn: "Vietnam", regionCode: "SOUTHEAST_ASIA" },
  { iso2: "TH", iso3: "THA", nameKo: "태국", nameEn: "Thailand", regionCode: "SOUTHEAST_ASIA" },
  { iso2: "ID", iso3: "IDN", nameKo: "인도네시아", nameEn: "Indonesia", regionCode: "SOUTHEAST_ASIA" },
  { iso2: "MY", iso3: "MYS", nameKo: "말레이시아", nameEn: "Malaysia", regionCode: "SOUTHEAST_ASIA" },
  { iso2: "IN", iso3: "IND", nameKo: "인도", nameEn: "India", regionCode: "SOUTH_ASIA" },
  { iso2: "US", iso3: "USA", nameKo: "미국", nameEn: "United States", regionCode: "NORTH_AMERICA" },
  { iso2: "CA", iso3: "CAN", nameKo: "캐나다", nameEn: "Canada", regionCode: "NORTH_AMERICA" },
  { iso2: "MX", iso3: "MEX", nameKo: "멕시코", nameEn: "Mexico", regionCode: "NORTH_AMERICA" },
  { iso2: "DE", iso3: "DEU", nameKo: "독일", nameEn: "Germany", regionCode: "EUROPE" },
  { iso2: "NL", iso3: "NLD", nameKo: "네덜란드", nameEn: "Netherlands", regionCode: "EUROPE" },
  { iso2: "GB", iso3: "GBR", nameKo: "영국", nameEn: "United Kingdom", regionCode: "EUROPE" },
  { iso2: "FR", iso3: "FRA", nameKo: "프랑스", nameEn: "France", regionCode: "EUROPE" },
  { iso2: "IT", iso3: "ITA", nameKo: "이탈리아", nameEn: "Italy", regionCode: "EUROPE" },
  { iso2: "ES", iso3: "ESP", nameKo: "스페인", nameEn: "Spain", regionCode: "EUROPE" },
  { iso2: "AE", iso3: "ARE", nameKo: "아랍에미리트", nameEn: "United Arab Emirates", regionCode: "MIDDLE_EAST" },
  { iso2: "SA", iso3: "SAU", nameKo: "사우디아라비아", nameEn: "Saudi Arabia", regionCode: "MIDDLE_EAST" },
  { iso2: "AU", iso3: "AUS", nameKo: "호주", nameEn: "Australia", regionCode: "OCEANIA" },
  { iso2: "NZ", iso3: "NZL", nameKo: "뉴질랜드", nameEn: "New Zealand", regionCode: "OCEANIA" },
] as const;

type LocationSeed = {
  countryIso2: string;
  type: "PORT" | "AIRPORT";
  code: string;
  unLocode?: string;
  iataCode?: string;
  nameKo: string;
  nameEn: string;
  timezone: string;
};

export const LOCATION_SEEDS: readonly LocationSeed[] = [
  { countryIso2: "KR", type: "PORT", code: "PORT-KRPUS", unLocode: "KRPUS", nameKo: "부산항", nameEn: "Port of Busan", timezone: "Asia/Seoul" },
  { countryIso2: "KR", type: "PORT", code: "PORT-KRINC", unLocode: "KRINC", nameKo: "인천항", nameEn: "Port of Incheon", timezone: "Asia/Seoul" },
  { countryIso2: "KR", type: "AIRPORT", code: "AIR-ICN", iataCode: "ICN", nameKo: "인천국제공항", nameEn: "Incheon International Airport", timezone: "Asia/Seoul" },
  { countryIso2: "KR", type: "AIRPORT", code: "AIR-PUS", iataCode: "PUS", nameKo: "김해국제공항", nameEn: "Gimhae International Airport", timezone: "Asia/Seoul" },
  { countryIso2: "KR", type: "AIRPORT", code: "AIR-GMP", iataCode: "GMP", nameKo: "김포국제공항", nameEn: "Gimpo International Airport", timezone: "Asia/Seoul" },
  { countryIso2: "CN", type: "PORT", code: "PORT-CNSHA", unLocode: "CNSHA", nameKo: "상하이항", nameEn: "Port of Shanghai", timezone: "Asia/Shanghai" },
  { countryIso2: "CN", type: "PORT", code: "PORT-CNNGB", unLocode: "CNNGB", nameKo: "닝보항", nameEn: "Port of Ningbo-Zhoushan", timezone: "Asia/Shanghai" },
  { countryIso2: "CN", type: "PORT", code: "PORT-CNSZX", unLocode: "CNSZX", nameKo: "선전항", nameEn: "Port of Shenzhen", timezone: "Asia/Shanghai" },
  { countryIso2: "CN", type: "PORT", code: "PORT-CNTAO", unLocode: "CNTAO", nameKo: "칭다오항", nameEn: "Port of Qingdao", timezone: "Asia/Shanghai" },
  { countryIso2: "CN", type: "AIRPORT", code: "AIR-PVG", iataCode: "PVG", nameKo: "상하이 푸둥 국제공항", nameEn: "Shanghai Pudong International Airport", timezone: "Asia/Shanghai" },
  { countryIso2: "CN", type: "AIRPORT", code: "AIR-PEK", iataCode: "PEK", nameKo: "베이징 수도 국제공항", nameEn: "Beijing Capital International Airport", timezone: "Asia/Shanghai" },
  { countryIso2: "CN", type: "AIRPORT", code: "AIR-CAN", iataCode: "CAN", nameKo: "광저우 바이윈 국제공항", nameEn: "Guangzhou Baiyun International Airport", timezone: "Asia/Shanghai" },
  { countryIso2: "CN", type: "AIRPORT", code: "AIR-SZX", iataCode: "SZX", nameKo: "선전 바오안 국제공항", nameEn: "Shenzhen Bao'an International Airport", timezone: "Asia/Shanghai" },
  { countryIso2: "JP", type: "PORT", code: "PORT-JPTYO", unLocode: "JPTYO", nameKo: "도쿄항", nameEn: "Port of Tokyo", timezone: "Asia/Tokyo" },
  { countryIso2: "JP", type: "PORT", code: "PORT-JPYOK", unLocode: "JPYOK", nameKo: "요코하마항", nameEn: "Port of Yokohama", timezone: "Asia/Tokyo" },
  { countryIso2: "JP", type: "PORT", code: "PORT-JPUKB", unLocode: "JPUKB", nameKo: "고베항", nameEn: "Port of Kobe", timezone: "Asia/Tokyo" },
  { countryIso2: "JP", type: "AIRPORT", code: "AIR-NRT", iataCode: "NRT", nameKo: "나리타 국제공항", nameEn: "Narita International Airport", timezone: "Asia/Tokyo" },
  { countryIso2: "JP", type: "AIRPORT", code: "AIR-HND", iataCode: "HND", nameKo: "도쿄 하네다 공항", nameEn: "Tokyo Haneda Airport", timezone: "Asia/Tokyo" },
  { countryIso2: "JP", type: "AIRPORT", code: "AIR-KIX", iataCode: "KIX", nameKo: "간사이 국제공항", nameEn: "Kansai International Airport", timezone: "Asia/Tokyo" },
  { countryIso2: "HK", type: "PORT", code: "PORT-HKHKG", unLocode: "HKHKG", nameKo: "홍콩항", nameEn: "Port of Hong Kong", timezone: "Asia/Hong_Kong" },
  { countryIso2: "HK", type: "AIRPORT", code: "AIR-HKG", iataCode: "HKG", nameKo: "홍콩 국제공항", nameEn: "Hong Kong International Airport", timezone: "Asia/Hong_Kong" },
  { countryIso2: "TW", type: "PORT", code: "PORT-TWKHH", unLocode: "TWKHH", nameKo: "가오슝항", nameEn: "Port of Kaohsiung", timezone: "Asia/Taipei" },
  { countryIso2: "TW", type: "PORT", code: "PORT-TWKEL", unLocode: "TWKEL", nameKo: "지룽항", nameEn: "Port of Keelung", timezone: "Asia/Taipei" },
  { countryIso2: "TW", type: "AIRPORT", code: "AIR-TPE", iataCode: "TPE", nameKo: "타오위안 국제공항", nameEn: "Taiwan Taoyuan International Airport", timezone: "Asia/Taipei" },
  { countryIso2: "TW", type: "AIRPORT", code: "AIR-KHH", iataCode: "KHH", nameKo: "가오슝 국제공항", nameEn: "Kaohsiung International Airport", timezone: "Asia/Taipei" },
  { countryIso2: "SG", type: "PORT", code: "PORT-SGSIN", unLocode: "SGSIN", nameKo: "싱가포르항", nameEn: "Port of Singapore", timezone: "Asia/Singapore" },
  { countryIso2: "SG", type: "AIRPORT", code: "AIR-SIN", iataCode: "SIN", nameKo: "싱가포르 창이 공항", nameEn: "Singapore Changi Airport", timezone: "Asia/Singapore" },
  { countryIso2: "VN", type: "PORT", code: "PORT-VNHPH", unLocode: "VNHPH", nameKo: "하이퐁항", nameEn: "Port of Hai Phong", timezone: "Asia/Ho_Chi_Minh" },
  { countryIso2: "VN", type: "PORT", code: "PORT-VNSGN", unLocode: "VNSGN", nameKo: "호찌민항", nameEn: "Port of Ho Chi Minh City", timezone: "Asia/Ho_Chi_Minh" },
  { countryIso2: "VN", type: "AIRPORT", code: "AIR-HAN", iataCode: "HAN", nameKo: "노이바이 국제공항", nameEn: "Noi Bai International Airport", timezone: "Asia/Ho_Chi_Minh" },
  { countryIso2: "VN", type: "AIRPORT", code: "AIR-SGN", iataCode: "SGN", nameKo: "떤선녓 국제공항", nameEn: "Tan Son Nhat International Airport", timezone: "Asia/Ho_Chi_Minh" },
  { countryIso2: "TH", type: "PORT", code: "PORT-THLCH", unLocode: "THLCH", nameKo: "램차방항", nameEn: "Port of Laem Chabang", timezone: "Asia/Bangkok" },
  { countryIso2: "TH", type: "AIRPORT", code: "AIR-BKK", iataCode: "BKK", nameKo: "수완나품 공항", nameEn: "Suvarnabhumi Airport", timezone: "Asia/Bangkok" },
  { countryIso2: "ID", type: "PORT", code: "PORT-IDTPP", unLocode: "IDTPP", nameKo: "탄중프리옥항", nameEn: "Port of Tanjung Priok", timezone: "Asia/Jakarta" },
  { countryIso2: "ID", type: "AIRPORT", code: "AIR-CGK", iataCode: "CGK", nameKo: "수카르노 하타 국제공항", nameEn: "Soekarno-Hatta International Airport", timezone: "Asia/Jakarta" },
  { countryIso2: "MY", type: "PORT", code: "PORT-MYPKG", unLocode: "MYPKG", nameKo: "포트클랑", nameEn: "Port Klang", timezone: "Asia/Kuala_Lumpur" },
  { countryIso2: "MY", type: "AIRPORT", code: "AIR-KUL", iataCode: "KUL", nameKo: "쿠알라룸푸르 국제공항", nameEn: "Kuala Lumpur International Airport", timezone: "Asia/Kuala_Lumpur" },
  { countryIso2: "IN", type: "PORT", code: "PORT-INNSA", unLocode: "INNSA", nameKo: "나바셰바항", nameEn: "Nhava Sheva Port", timezone: "Asia/Kolkata" },
  { countryIso2: "IN", type: "PORT", code: "PORT-INMAA", unLocode: "INMAA", nameKo: "첸나이항", nameEn: "Port of Chennai", timezone: "Asia/Kolkata" },
  { countryIso2: "IN", type: "AIRPORT", code: "AIR-DEL", iataCode: "DEL", nameKo: "인디라 간디 국제공항", nameEn: "Indira Gandhi International Airport", timezone: "Asia/Kolkata" },
  { countryIso2: "IN", type: "AIRPORT", code: "AIR-BOM", iataCode: "BOM", nameKo: "차트라파티 시바지 국제공항", nameEn: "Chhatrapati Shivaji Maharaj International Airport", timezone: "Asia/Kolkata" },
  { countryIso2: "US", type: "PORT", code: "PORT-USLAX", unLocode: "USLAX", nameKo: "로스앤젤레스항", nameEn: "Port of Los Angeles", timezone: "America/Los_Angeles" },
  { countryIso2: "US", type: "PORT", code: "PORT-USLGB", unLocode: "USLGB", nameKo: "롱비치항", nameEn: "Port of Long Beach", timezone: "America/Los_Angeles" },
  { countryIso2: "US", type: "PORT", code: "PORT-USNYC", unLocode: "USNYC", nameKo: "뉴욕·뉴저지항", nameEn: "Port of New York and New Jersey", timezone: "America/New_York" },
  { countryIso2: "US", type: "PORT", code: "PORT-USSAV", unLocode: "USSAV", nameKo: "서배너항", nameEn: "Port of Savannah", timezone: "America/New_York" },
  { countryIso2: "US", type: "AIRPORT", code: "AIR-LAX", iataCode: "LAX", nameKo: "로스앤젤레스 국제공항", nameEn: "Los Angeles International Airport", timezone: "America/Los_Angeles" },
  { countryIso2: "US", type: "AIRPORT", code: "AIR-JFK", iataCode: "JFK", nameKo: "존 F. 케네디 국제공항", nameEn: "John F. Kennedy International Airport", timezone: "America/New_York" },
  { countryIso2: "US", type: "AIRPORT", code: "AIR-ORD", iataCode: "ORD", nameKo: "시카고 오헤어 국제공항", nameEn: "O'Hare International Airport", timezone: "America/Chicago" },
  { countryIso2: "US", type: "AIRPORT", code: "AIR-SEA", iataCode: "SEA", nameKo: "시애틀 터코마 국제공항", nameEn: "Seattle-Tacoma International Airport", timezone: "America/Los_Angeles" },
  { countryIso2: "US", type: "AIRPORT", code: "AIR-DFW", iataCode: "DFW", nameKo: "댈러스 포트워스 국제공항", nameEn: "Dallas Fort Worth International Airport", timezone: "America/Chicago" },
  { countryIso2: "US", type: "AIRPORT", code: "AIR-MIA", iataCode: "MIA", nameKo: "마이애미 국제공항", nameEn: "Miami International Airport", timezone: "America/New_York" },
  { countryIso2: "CA", type: "PORT", code: "PORT-CAVAN", unLocode: "CAVAN", nameKo: "밴쿠버항", nameEn: "Port of Vancouver", timezone: "America/Vancouver" },
  { countryIso2: "CA", type: "AIRPORT", code: "AIR-YVR", iataCode: "YVR", nameKo: "밴쿠버 국제공항", nameEn: "Vancouver International Airport", timezone: "America/Vancouver" },
  { countryIso2: "CA", type: "AIRPORT", code: "AIR-YYZ", iataCode: "YYZ", nameKo: "토론토 피어슨 국제공항", nameEn: "Toronto Pearson International Airport", timezone: "America/Toronto" },
  { countryIso2: "CA", type: "AIRPORT", code: "AIR-YUL", iataCode: "YUL", nameKo: "몬트리올 트뤼도 국제공항", nameEn: "Montréal-Trudeau International Airport", timezone: "America/Toronto" },
  { countryIso2: "MX", type: "PORT", code: "PORT-MXZLO", unLocode: "MXZLO", nameKo: "만사니요항", nameEn: "Port of Manzanillo", timezone: "America/Mexico_City" },
  { countryIso2: "MX", type: "AIRPORT", code: "AIR-MEX", iataCode: "MEX", nameKo: "멕시코시티 국제공항", nameEn: "Mexico City International Airport", timezone: "America/Mexico_City" },
  { countryIso2: "DE", type: "PORT", code: "PORT-DEHAM", unLocode: "DEHAM", nameKo: "함부르크항", nameEn: "Port of Hamburg", timezone: "Europe/Berlin" },
  { countryIso2: "DE", type: "AIRPORT", code: "AIR-FRA", iataCode: "FRA", nameKo: "프랑크푸르트 공항", nameEn: "Frankfurt Airport", timezone: "Europe/Berlin" },
  { countryIso2: "NL", type: "PORT", code: "PORT-NLRTM", unLocode: "NLRTM", nameKo: "로테르담항", nameEn: "Port of Rotterdam", timezone: "Europe/Amsterdam" },
  { countryIso2: "NL", type: "AIRPORT", code: "AIR-AMS", iataCode: "AMS", nameKo: "암스테르담 스키폴 공항", nameEn: "Amsterdam Airport Schiphol", timezone: "Europe/Amsterdam" },
  { countryIso2: "GB", type: "PORT", code: "PORT-GBFXT", unLocode: "GBFXT", nameKo: "펠릭스토항", nameEn: "Port of Felixstowe", timezone: "Europe/London" },
  { countryIso2: "GB", type: "AIRPORT", code: "AIR-LHR", iataCode: "LHR", nameKo: "런던 히드로 공항", nameEn: "London Heathrow Airport", timezone: "Europe/London" },
  { countryIso2: "FR", type: "PORT", code: "PORT-FRLEH", unLocode: "FRLEH", nameKo: "르아브르항", nameEn: "Port of Le Havre", timezone: "Europe/Paris" },
  { countryIso2: "FR", type: "AIRPORT", code: "AIR-CDG", iataCode: "CDG", nameKo: "파리 샤를 드골 공항", nameEn: "Paris Charles de Gaulle Airport", timezone: "Europe/Paris" },
  { countryIso2: "IT", type: "PORT", code: "PORT-ITGOA", unLocode: "ITGOA", nameKo: "제노바항", nameEn: "Port of Genoa", timezone: "Europe/Rome" },
  { countryIso2: "IT", type: "AIRPORT", code: "AIR-MXP", iataCode: "MXP", nameKo: "밀라노 말펜사 공항", nameEn: "Milan Malpensa Airport", timezone: "Europe/Rome" },
  { countryIso2: "ES", type: "PORT", code: "PORT-ESVLC", unLocode: "ESVLC", nameKo: "발렌시아항", nameEn: "Port of Valencia", timezone: "Europe/Madrid" },
  { countryIso2: "ES", type: "AIRPORT", code: "AIR-MAD", iataCode: "MAD", nameKo: "마드리드 바라하스 공항", nameEn: "Adolfo Suárez Madrid-Barajas Airport", timezone: "Europe/Madrid" },
  { countryIso2: "AE", type: "PORT", code: "PORT-AEJEA", unLocode: "AEJEA", nameKo: "제벨알리항", nameEn: "Port of Jebel Ali", timezone: "Asia/Dubai" },
  { countryIso2: "AE", type: "AIRPORT", code: "AIR-DXB", iataCode: "DXB", nameKo: "두바이 국제공항", nameEn: "Dubai International Airport", timezone: "Asia/Dubai" },
  { countryIso2: "AE", type: "AIRPORT", code: "AIR-AUH", iataCode: "AUH", nameKo: "자이드 국제공항", nameEn: "Zayed International Airport", timezone: "Asia/Dubai" },
  { countryIso2: "SA", type: "PORT", code: "PORT-SAJED", unLocode: "SAJED", nameKo: "제다항", nameEn: "Jeddah Islamic Port", timezone: "Asia/Riyadh" },
  { countryIso2: "SA", type: "AIRPORT", code: "AIR-JED", iataCode: "JED", nameKo: "킹 압둘아지즈 국제공항", nameEn: "King Abdulaziz International Airport", timezone: "Asia/Riyadh" },
  { countryIso2: "AU", type: "PORT", code: "PORT-AUSYD", unLocode: "AUSYD", nameKo: "시드니항", nameEn: "Port of Sydney", timezone: "Australia/Sydney" },
  { countryIso2: "AU", type: "PORT", code: "PORT-AUMEL", unLocode: "AUMEL", nameKo: "멜버른항", nameEn: "Port of Melbourne", timezone: "Australia/Melbourne" },
  { countryIso2: "AU", type: "AIRPORT", code: "AIR-SYD", iataCode: "SYD", nameKo: "시드니 공항", nameEn: "Sydney Airport", timezone: "Australia/Sydney" },
  { countryIso2: "AU", type: "AIRPORT", code: "AIR-MEL", iataCode: "MEL", nameKo: "멜버른 공항", nameEn: "Melbourne Airport", timezone: "Australia/Melbourne" },
  { countryIso2: "NZ", type: "PORT", code: "PORT-NZAKL", unLocode: "NZAKL", nameKo: "오클랜드항", nameEn: "Port of Auckland", timezone: "Pacific/Auckland" },
  { countryIso2: "NZ", type: "AIRPORT", code: "AIR-AKL", iataCode: "AKL", nameKo: "오클랜드 공항", nameEn: "Auckland Airport", timezone: "Pacific/Auckland" },
];
